# Generated by Django 5.1.2 on 2024-10-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default="9446900640", max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
