# Generated by Django 5.1.2 on 2024-11-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_dna_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dna_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Unique DNA identifier.",
                max_length=20,
                unique=True,
            ),
        ),
    ]
