# Generated by Django 5.1.2 on 2024-10-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0002_remove_program_participants_event_participants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="participants",
        ),
        migrations.RemoveField(
            model_name="program",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="program",
            name="start_date",
        ),
    ]
