# Generated by Django 5.1.2 on 2024-11-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0003_remove_event_participants_remove_program_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.DecimalField(decimal_places=2, default="2", max_digits=5),
            preserve_default=False,
        ),
    ]
