# Generated by Django 5.1.2 on 2024-11-05 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0004_event_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Default price if no registration types",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RegistrationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_types",
                        to="programs.event",
                    ),
                ),
            ],
        ),
    ]
