# Generated by Django 5.1.2 on 2024-11-05 05:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["user", "otp_type", "is_used"],
                name="verificatio_user_id_4cfd21_idx",
            ),
        ),
    ]
