# Generated by Django 5.1.2 on 2024-11-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="participated",
            field=models.BooleanField(default=False),
        ),
    ]
