# Generated by Django 5.1.2 on 2024-11-14 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="registration",
            name="unique_registration",
        ),
    ]
