# Generated by Django 5.1.2 on 2024-11-01 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0003_remove_event_participants_remove_program_end_date_and_more"),
        ("registrations", "0002_registration_participated"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="program",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="programs.program",
            ),
            preserve_default=False,
        ),
    ]
