# Generated by Django 5.1.2 on 2024-11-18 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "registrations",
            "0003_rename_registration_date_registration_registered_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together=set(),
        ),
    ]
