# Generated by Django 5.1.2 on 2024-11-01 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0003_registration_program"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="program",
        ),
    ]
