# Generated by Django 5.1.2 on 2024-11-02 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0003_remove_event_participants_remove_program_end_date_and_more"),
        ("registrations", "0004_remove_registration_program"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                fields=("user", "event"), name="unique_registration"
            ),
        ),
    ]
