# Generated by Django 5.1.2 on 2024-11-05 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0005_alter_event_price_registrationtype"),
        ("registrations", "0005_alter_registration_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="registration_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registrations",
                to="programs.registrationtype",
            ),
        ),
    ]
