# Generated by Django 5.1.2 on 2024-11-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0005_alter_event_price_registrationtype"),
        ("registrations", "0006_registration_registration_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percentage"), ("fixed", "Fixed Amount")],
                        default="percent",
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                (
                    "registration_types",
                    models.ManyToManyField(blank=True, to="programs.registrationtype"),
                ),
            ],
        ),
    ]
