# Generated by Django 5.1.2 on 2024-11-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0007_discountcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration",
            old_name="is_confirmed",
            new_name="is_paid",
        ),
        migrations.RenameField(
            model_name="registration",
            old_name="confirmation_date",
            new_name="payment_date",
        ),
        migrations.DeleteModel(
            name="DiscountCode",
        ),
    ]
