# Generated by Django 5.1.2 on 2024-11-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0008_rename_is_confirmed_registration_is_paid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="registration_type",
        ),
    ]
