# Generated by Django 5.1.2 on 2024-11-05 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbadge",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badge_users",
                to="badges.badge",
            ),
        ),
        migrations.AlterField(
            model_name="userbadge",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_badges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
